# SwiftLint Configuration for HeyBoomerang iOS
# Based on modern Swift best practices for iOS 17+

# File and directory exclusions
excluded:
  - Carthage
  - Pods
  - .build
  - .swiftpm
  - DerivedData

# Optional rules to enable
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo # We'll use TODO: comments during development

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 600
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

type_name:
  min_length: 2
  max_length: 60

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - to
    - up
    - x
    - y

# Custom rules
custom_rules:
  force_unwrapping:
    name: "Force Unwrapping"
    regex: '(\!\s*)'
    message: "Avoid force unwrapping. Consider using optional binding or guard statements instead."
    severity: warning

  # Ensure proper spacing around operators
  operator_whitespace:
    name: "Operator Whitespace"
    regex: '(\S[\+\-\*\/\%\=\<\>\!\&\|\^]+\S|\S[\+\-\*\/\%\=\<\>\!\&\|\^]+|\S[\+\-\*\/\%\=\<\>\!\&\|\^]+\S)'
    message: "Operators should be surrounded by spaces"
    severity: warning

# File header template (optional)
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  HeyBoomerangIOS
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2,4}\.
                    \/\/

# Minimum Swift version
swift_version: "5.10"